// <auto-generated />
using System;
using CarrierWebApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarrierWebApi.Migrations
{
    [DbContext(typeof(CarrierRegistrationDbContext))]
    [Migration("20240206051104_first migration")]
    partial class Firstmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarrierWebApi.Models.Certificates", b =>
                {
                    b.Property<long>("CertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CertificateId"));

                    b.Property<string>("DocumentReferenceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CertificateId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("CarrierWebApi.Models.CharactersDetails", b =>
                {
                    b.Property<long>("CharactersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CharactersId"));

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CharacteresCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Country")
                        .HasColumnType("int");

                    b.Property<string>("EmailID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipOwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CharactersId");

                    b.ToTable("CharactersDetails");
                });

            modelBuilder.Entity("CarrierWebApi.Models.ShipOwnerDetails", b =>
                {
                    b.Property<long>("ShipOwnerDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ShipOwnerDetailsId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Country")
                        .HasColumnType("int");

                    b.Property<string>("EmailID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MobileNo")
                        .HasColumnType("int");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("ShipOwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShipOwnerDetailsId");

                    b.ToTable("ShipOwnerDetails");
                });

            modelBuilder.Entity("CarrierWebApi.Models.VesselRegistration", b =>
                {
                    b.Property<long>("VesselId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VesselId"));

                    b.Property<string>("ApplicantRemarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AreaofOperation")
                        .HasColumnType("int");

                    b.Property<int>("Beam")
                        .HasColumnType("int");

                    b.Property<string>("CallSignNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CargoType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CertificateRegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeadWeight")
                        .HasColumnType("int");

                    b.Property<int>("DisplacementWeight")
                        .HasColumnType("int");

                    b.Property<string>("FlagStateofShip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GrossRegistrationTons")
                        .HasColumnType("int");

                    b.Property<string>("IMONo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameofShip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalityofShip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PandIclub")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortofRegistration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionofBridge")
                        .HasColumnType("int");

                    b.Property<DateTime>("Registrationdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShipIdentificationNo")
                        .HasColumnType("int");

                    b.Property<int>("StandradDraught")
                        .HasColumnType("int");

                    b.Property<int>("TypeofHull")
                        .HasColumnType("int");

                    b.Property<int>("VesselCapacity")
                        .HasColumnType("int");

                    b.Property<int>("VesselTerm")
                        .HasColumnType("int");

                    b.Property<int>("VesselTrade")
                        .HasColumnType("int");

                    b.Property<int>("VesselType")
                        .HasColumnType("int");

                    b.Property<string>("YearBuilt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VesselId");

                    b.ToTable("VesselRegistrations");
                });
#pragma warning restore 612, 618
        }
    }
}
